services:
    redpanda:
        image: redpandadata/redpanda:latest
        container_name: redpanda
        command:
            - redpanda
            - start
            - --kafka-addr=internal://0.0.0.0:29092,external://0.0.0.0:9092
            - --advertise-kafka-addr=internal://redpanda:29092,external://localhost:9092
            - --smp=1
            - --memory=1G
            - --overprovisioned
            - --node-id=0
            - --check=false
        ports:
            - "9092:9092"
            - "9644:9644"

    console:
        image: redpandadata/console:latest
        container_name: redpanda-console
        depends_on:
            - redpanda
        ports:
            - "8080:8080"
        environment:
            KAFKA_BROKERS: redpanda:29092
